const employee = [
  {
    id: 1,
    name: "Ali Khan",
    email: "ali@gmail.com",
    phone: "9876543210",
    address: "New Delhi",
    companyName: "TechSoft",
  },
  {
    id: 2,
    name: "Ahmed Raza",
    email: "ahmed@gmail.com",
    phone: "9876543211",
    address: "Lucknow",
    companyName: "CodeCraft",
  },
  {
    id: 3,
    name: "Sara Noor",
    email: "sara@gmail.com",
    phone: "9876543212",
    address: "Mumbai",
    companyName: "Webify",
  },
  {
    id: 4,
    name: "Ayaan Sheikh",
    email: "ayaan@gmail.com",
    phone: "9876543213",
    address: "Bangalore",
    companyName: "InnoTech",
  },
  {
    id: 5,
    name: "Zoya Ali",
    email: "zoya@gmail.com",
    phone: "9876543214",
    address: "Hyderabad",
    companyName: "DevStudio",
  },
  {
    id: 6,
    name: "Hamza Khan",
    email: "hamza@gmail.com",
    phone: "9876543215",
    address: "Pune",
    companyName: "NextGen Labs",
  },
  {
    id: 7,
    name: "Fatima Rizvi",
    email: "fatima@gmail.com",
    phone: "9876543216",
    address: "Bhopal",
    companyName: "SoftEdge",
  },
  {
    id: 8,
    name: "Usman Farooq",
    email: "usman@gmail.com",
    phone: "9876543217",
    address: "Jaipur",
    companyName: "CloudNine",
  },
  {
    id: 9,
    name: "Aisha Siddiqui",
    email: "aisha@gmail.com",
    phone: "9876543218",
    address: "Kolkata",
    companyName: "AppWorks",
  },
  {
    id: 10,
    name: "Bilal Ansari",
    email: "bilal@gmail.com",
    phone: "9876543219",
    address: "Chennai",
    companyName: "DigitalFlow",
  },
];

export default employee;
